music_exec: "MUSIC"
parent_setups:
  parent3:
    workdir: '/u/mfrigo/Software/zoomictools/parent3'
    parent_snaps: '/ptmp/mpa/mfrigo/musicsims/parent3/snap_parent_'
    parent_ic: '/ptmp/mpa/mfrigo/musicsims/parent3/parent.gdt'
    cosmology: 'planck'
    boxsize: 72
    zstart: 43.029476
    seedsset: [12345, 23336, 34567, 12146, 23111, 24343, 45454, 87654, 98765, 34987]
    parentres: 9
    lowestres: 4
  P200:
    workdir: '/ptmp/mpa/mhirsch/P200/'
    parent_snaps:
      - "/ptmp/mpa/loser/SIMULATIONS/P200/snapdir_"
      - "/snap_P200_"
    parent_ic: "/ptmp/mpa/loser/SIMULATIONS/P200/IC/ics_200Mpc_planck.dat"
    cosmology: 'planck'
    boxsize: 135.54
    zstart: 63.
    seedsset: [12345, 23456, 34567, 90341, 56789, 67890, 45454, 87654, 98765, 34987]
    parentres: 10
    lowestres: 5